# Dockerfile.frontend

# Base stage
FROM node:20-alpine AS builder
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

# Production image
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app ./
ENV HOST 0.0.0.0
EXPOSE 3001

CMD ["npm", "run", "start"]
