FROM node:18-alpine AS builder

WORKDIR /app
COPY backend ./backend
WORKDIR /app/backend

RUN npm install
RUN npx nx run-many --target=build --all

# -------------------------------------------

FROM node:18-alpine AS runner
WORKDIR /app

# ✅ Copy all built apps (e.g., dist/apps/api-gateway)
COPY --from=builder /app/backend/dist ./dist

COPY backend/package.json .

# ✅ Start the correct microservice manually
# CMD ["node", "dist/apps/api-gateway/main.js"]
